services:
  - type: web
    name: flask-mongodb-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn mon:app
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://shawondata:shawondata@cluster0.sigdzxx.mongodb.net/shawon?retryWrites=true&w=majority
